name: tailscale derp disable hostname checking
on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - 'Dockerfile'
      - 'entrypoint.sh'
  workflow_run:
    workflows: ["Update Tailscale"]
    types:
      - completed
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive
          fetch-depth: 2

      - name: Trigger type
        run: |
          if [ "${{ github.event_name }}" == "workflow_run" ]; then
            echo "trigger_type=workflow_run" >> $GITHUB_ENV
          else
            echo "trigger_type=others" >> $GITHUB_ENV
          fi
      - name: Check for derper changes (Only for submodule updates)
        if: env.trigger_type == 'workflow_run'
        run: |
          git diff HEAD^ HEAD --quiet third_party/tailscale/cmd/derper/ && echo "trigger_deploy=false" >> $GITHUB_ENV || echo "trigger_deploy=true" >> $GITHUB_ENV

      - name: Deploy if required
        run: |
          if [[ "$trigger_type" == "others" || "$trigger_deploy" == "true" ]]; then
            echo "Deploying..."
          else
            echo "No deploy needed."
            exit 0
          fi

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
        if: env.trigger_type == 'others' || env.trigger_deploy == 'true'
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
        if: env.trigger_type == 'others' || env.trigger_deploy == 'true'
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        if: env.trigger_type == 'others' || env.trigger_deploy == 'true'
        with:
          username: ${{ vars.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        if: env.trigger_type == 'others' || env.trigger_deploy == 'true'
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push Docker images to docker.io and ghcr.io
        uses: docker/build-push-action@v6
        if: env.trigger_type == 'others' || env.trigger_deploy == 'true'
        with:
          platforms: linux/amd64,linux/arm64
          context: .
          push: true
          tags: |
            camllia/derper:latest
            camllia/derper:${{github.sha}}
            ghcr.io/xavieralpha/derper:latest
