name: Update Tailscale

on:
  schedule:
    - cron: '0 0 * * *'
  workflow_dispatch:

jobs:
  update_tailscale:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout main repository
        uses: actions/checkout@v4
        with:
          submodules: true
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Update
        run: |
          git submodule update --remote --recursive
          if git diff --exit-code; then
            echo "No changes to commit."
          else
            git config --global user.name "Gitbot"
            git config --global user.email "bot@noreply.github.com"
            git commit -am "Update tailscale to latest commit [skip ci]"
            git push origin "${{ github.ref }}"
          fi
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
